#root = TreeNode.create name: 'root'

#root.children.create name: '', common_name: 'Liverworts', note: ''
#root.children.create name: '', common_name: 'Mosses', note: ''
#root.children.create name: '', common_name: 'Hornworts', note: ''
#root.children.create name: '', common_name: 'Lycophytes', note: ''

ferns = TreeNode.create name: 'Monilophytes', common_name: 'Ferns', note: ''

seed_plants = TreeNode.create name: 'Spermatophyte', common_name: 'Seed Plants', note: '' 

gmyno = seed_plants.children.create name: 'Gymnosperms', common_name: 'Gymnosperm', note: ''
  gmyno.children.create name: 'Cycadales', common_name: 'Palm', note: ''
  gmyno.children.create name: 'Ginkgoales', common_name: 'Ginkgo', note: ''
#  gmyno.children.create name: '', common_name: 'Ephedra', note: ''
#  gmyno.children.create name: '', common_name: 'Welwitschia', note: ''
  gmyno.children.create name: 'Gnetales', common_name: 'Gnetum', note: ''
  gmyno.children.create name: 'Pinales', common_name: 'Pine', note: ''
 
angio = seed_plants.children.create name: 'Angiosperms', common_name: 'Flowering Plants', note: ''

  anita = angio.children.create name: 'Anita', common_name: 'ANA-Grade', note: ''
    anita.children.create name: "Amborellales", common_name: 'Amborellales', note: 'woody, vessels lacking; dioecious; flw T5–8, A∞, G5–8; 1 ovule/carpel; embryo sac 9-nucleate; 1 species (New Caledonia)'
    anita.children.create name: "Nymphaeales", common_name: 'Water lilies', note: 'aquatic, herbaceous; cambium absent; aerenchyma; flw T4–12, A3–∞; embryo sac 4-nucleate seeds operculate, perisperm; mucilage; alkaloids (no benzylisoquinolines)'
    anita.children.create name: 'Austrobaileyales', common_name: 'Austrobaileyales', note: 'woody, vessels solitary; flw T>10, A∞, G ca.9; embryo sac 4-nucleate tiglic acid, aromatic terpenoids'
  
  angio.children.create name: 'Chloranthales', common_name: 'Chloranthales', note: ''

  magno = angio.children.create name: 'Magnoliids', common_name: 'Magnoliids', note: ''
    magno.children.create name: 'Canellales', common_name: 'Canellales', note: ''
    magno.children.create name: 'Piperales', common_name: 'Piperales', note: ''
    magno.children.create name: 'Laurales', common_name: 'Laurales', note: ''
    magno.children.create name: 'Magnoliales', common_name: 'Magnoliales', note: ''    

  mono = angio.children.create name: 'Monocots', common_name: 'Monocots', note: ''
    mono.children.create name: 'Acorales', common_name: 'Acorales', note: ''
    mono.children.create name: 'Alismatales', common_name: 'Alismatales', note: ''
    mono.children.create name: 'Petrosaviales', common_name: 'Petrosaviales', note: ''
    mono.children.create name: 'Dioscoreales', common_name: 'Dioscoreales', note: ''
    mono.children.create name: 'Pandanales', common_name: 'Pandanales', note: ''
    mono.children.create name: 'Liliales', common_name: 'Liliales', note: ''
    mono.children.create name: 'Asparagales', common_name: 'Asparagales', note: ''

    comme = mono.children.create name: 'Commelinids', common_name: 'Commelinids', note: ''
      comme.children.create name: 'Arecales', common_name: 'Arecales', note: ''
      comme.children.create name: 'Poales', common_name: 'Poales', note: ''
      comme.children.create name: 'Commelinales', common_name: 'Commelinales', note: ''
      comme.children.create name: 'Zingiberales', common_name: 'Zingiberales', note: ''

  dicot = angio.children.create name: 'Eudicots', common_name: 'Eudicots', note: ''
      dicot.children.create name: 'Ceratophyllales', common_name: 'Ceratophyllales', note: ''
      dicot.children.create name: 'Ranunculales', common_name: 'Ranunculales', note: ''
      dicot.children.create name: 'Sabiales', common_name: 'Sabiales', note: ''
      dicot.children.create name: 'Proteales', common_name: 'Proteales', note: ''
      dicot.children.create name: 'Trochodendrales', common_name: 'Trochodendrales', note: ''
      dicot.children.create name: 'Buxales', common_name: 'Buxales', note: ''

      core = dicot.children.create name: 'Core eudicots', common_name: 'Core eudicots', note: ''
        core.children.create name: 'Gunnerales', common_name: 'Gunnerales', note: ''
        core.children.create name: 'Dilleniales', common_name: 'Dilleniales', note: ''
        
        rosid = core.children.create name: 'Rosids', common_name: 'Rosids', note: ''
          rosid.children.create name: 'Saxifragales', common_name: 'Saxifragales', note: ''
          rosid.children.create name: 'Vitales', common_name: 'Vitales', note: ''

          fab = rosid.children.create name: 'Fabids', common_name: 'Fabids', note: ''
            fab.children.create name: 'Zygophyllales', common_name: 'Zygophyllales', note: ''
            fab.children.create name: 'Celastrales', common_name: 'Celastrales', note: ''
            fab.children.create name: 'Oxalidales', common_name: 'Oxalidales', note: ''
            fab.children.create name: 'Malpighiales', common_name: 'Malpighiales', note: ''
            fab.children.create name: 'Fabales', common_name: 'Fabales', note: ''
            fab.children.create name: 'Rosales', common_name: 'Rosales', note: ''
            fab.children.create name: 'Cucurbitales', common_name: 'Cucurbitales', note: ''
            fab.children.create name: 'Fagales', common_name: 'Fagales', note: ''

          mal = rosid.children.create name: 'Malvids', common_name: 'Malvids', note: ''
            mal.children.create name: 'Geraniales', common_name: 'Geraniales', note: ''
            mal.children.create name: 'Myrtales', common_name: 'Myrtales', note: ''
            mal.children.create name: 'Crossosomatales', common_name: 'Crossosomatales', note: ''
            mal.children.create name: 'Picramniales', common_name: 'Picramniales', note: ''
            mal.children.create name: 'Sapindales', common_name: 'Sapindales', note: ''
            mal.children.create name: 'Huerteales', common_name: 'Huerteales', note: ''
            mal.children.create name: 'Malvales', common_name: 'Malvales', note: ''
            mal.children.create name: 'Brassicales', common_name: 'Brassicales', note: ''
        
        core.children.create name: 'Santalales', common_name: 'Santalales', note: ''
        core.children.create name: 'Berberidopsidales', common_name: 'Berberidopsidales', note: ''
        core.children.create name: 'Caryophyllales', common_name: 'Caryophyllales', note: ''
            
        asterid = core.children.create name: 'Asterid', common_name: 'Asterid', note: ''
          asterid.children.create name: 'Cornales', common_name: 'Cornales', note: ''
          asterid.children.create name: 'Ericales', common_name: 'Ericales', note: ''
          
          lam = asterid.children.create name: 'Lamiids', common_name: 'Lamiids', note: ''
            lam.children.create name: 'Garryales', common_name: 'Garryales', note: ''
            lam.children.create name: 'Gentianales', common_name: 'Gentianales', note: ''
            lam.children.create name: 'Solanales', common_name: 'Solanales', note: ''
            lam.children.create name: 'Lamiales', common_name: 'Lamiales', note: ''
            lam.children.create name: 'Boraginales', common_name: 'Boraginales', note: ''
            
          camp = asterid.children.create name: 'Campanulids', common_name: 'Campanulids', note: ''
            camp.children.create name: 'Aquifoliales', common_name: 'Aquifoliales', note: ''
            camp.children.create name: 'Asterales', common_name: 'Asterales', note: ''
            camp.children.create name: 'Escalloniales', common_name: 'Escalloniales', note: ''
            camp.children.create name: 'Bruniales', common_name: 'Bruniales', note: ''
            camp.children.create name: 'Apiales', common_name: 'Apiales', note: ''
            camp.children.create name: 'Paracryphiales', common_name: 'Paracryphiales', note: ''
            camp.children.create name: 'Dipsacales', common_name: 'Dipsacales', note: ''
